"""Add user approval and activity status

Revision ID: 700b683f689f
Revises: d6f63628f89a
Create Date: 2025-09-19 16:24:57.943428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700b683f689f'
down_revision = 'd6f63628f89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('user', schema=None) as batch_op:
    batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
